name: context-action

on:
  push:
    branches:
      - main

env:
  v1: "new version"

jobs:
  context-action-setup:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: inital env
        env:
          secret: ${{ secrets.superstar }}
          action_status: "action status is success"
        run: node test.js
  context-testing:
    runs-on: ubuntu-18.04
    steps:
      - name: Dump github context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

      - name: Dump runner env
        run: echo '${{ env.v1 }}'

      - name: Dump single key-value env
        run: echo '${{ toJSON(env)}}'
