name: "Run test.js"
on:
  push:
    branches:
      - main

jobs:
  run-npm:
    runs-on: ubuntu-18.04
    steps:
      - run: "sudo apt-get update -y"
      - run: "sudo apt-get install node -y"
      - run: "node -v"

      - name: "Running the test.js script"
        run: node ../../test.js

      - name: "Finishing up the script"
        run: echo "Finished...."
