name: status-action

on:
  push:
    branches:
      - main
jobs:
  status-check:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3

      - run: echo "hello" > outputfile.log
      - run: cat outputfile.log
